# Schema for the theme setting configuration file of the THEMETITLE theme.

THEMENAME.settings:
  type: theme_settings
  label: 'una_examen settings'
  region_wells:
    navigation: ''
    navigation_collapsible: ''
    header: ''
    highlighted: ''
    help: ''
    content: ''
    sidebar_first: ''
    sidebar_second: ''
    footer: ''
